{
  "hash": "2bde46892a4942f39ebbdd819dd6c356",
  "result": {
    "markdown": "---\ntitle: 'PPM: Exploring 1^st^ order effects'\nauthor: \"Manny Gimond\"\n---\n\n\n\n\n------------------------------------------------------------------------\n\n[Data for this tutorial can be downloaded [from here](./data.zip). Don't forget to unzip the files to a dedicated folder on your computer.]{.block1}\n\n-----\n\n> Don't forget to set the R session to the project folder via *Session \\>\\> Set Working Directory \\>\\> Choose Directory*.\n\n-----\n\n## Loading the data into R\n\nFirst, we'll load the point pattern dataset, then we'll load two different raster datasets that will represent two separate 1^st^  order effects we suspect may help explain the distribution of stores within the study extent.\n\n\n::: {.cell hash='PPM_analysis_cache/html/unnamed-chunk-1_24c00444385a263d3de313e05f67601e'}\n\n```{.r .cell-code}\n# Load packages\n# Note that the rgdal package should also be installed on your computer \n# even though it's not explicitly loaded in the R code\nlibrary(spatstat)\nlibrary(maptools)\nlibrary(sf)\nlibrary(raster)\n\n# Read state polygon data\ns    <- st_read(\"MA.shp\")\nw    <- as.owin(s)\nw.km <- rescale(w, 1000)\n\n# Read Walmart point data\ns    <- st_read(\"Walmarts.shp\")\np    <- as.ppp(s)\np.km <- rescale(p, 1000)\nmarks(p.km)  <- NULL\nWindow(p.km) <- w.km\n\n# Read population density raster\nimg         <- raster(\"pop_sqmile.tif\")\npop         <- as.im(img)\npop.km      <- rescale(pop, 1000)\npop.km.log  <- log(pop.km)\n\n# Read median income raster\nimg      <- raster(\"median_income.tif\")\ninc      <- as.im(img)\ninc.km   <- rescale(inc, 1000)\ninc.km[] <- as.double(inc.km[]) # Convert integer income values to double values\n```\n:::\n\n\nYou'll note that we are converting the income raster from integer data type to double (`inc[] <- as.double(inc[])`). This is done to satisfy the `effectfun()` function that will be used later in this workflow--that function does *not* accept integer rasters.\n\nYou'll also note in the above chunk of code that we are **transforming** population density values to logged values (`log(pop.km)`) because of the **skewed nature** of the population raster. This may help improve the model performance. Such transformation techniques are not uncommon in the field of statistics.\n\nA quick way to check the distribution of raster pixel values is to plot the histogram as follows:\n\n\n::: {.cell hash='PPM_analysis_cache/html/unnamed-chunk-2_e1160cfb14a979a1fa5b9cdcc42bf3ae'}\n\n```{.r .cell-code}\n# Plot original raster values\nhist(pop.km)\n```\n\n::: {.cell-output-display}\n![](PPM_analysis_files/figure-html/unnamed-chunk-2-1.png){width=288}\n:::\n:::\n\n::: {.cell hash='PPM_analysis_cache/html/unnamed-chunk-3_2ff6962c4b202a31e2da1bbcc0bf85dc'}\n\n```{.r .cell-code}\n# Plot log-transformed raster values\nhist(pop.km.log)\n```\n\n::: {.cell-output-display}\n![](PPM_analysis_files/figure-html/unnamed-chunk-3-1.png){width=288}\n:::\n:::\n\n\nThe latter distribution of values is better suited for the ppm technique adopted in this exercise. \n\nLet's plot each raster with the Walmart point overlay. We'll use `R`'s base plotting environment.\n\n\n::: {.cell small.mar='true' hash='PPM_analysis_cache/html/unnamed-chunk-4_ac05c4bc25ffb4bd0a4d58ac5f9b090f'}\n\n```{.r .cell-code}\nplot(pop.km.log, ribside=\"bottom\", main=\"Population (log)\")\nplot(p.km, pch = 20, col=rgb(1,1,1,0.5), add=TRUE)\n\nplot(inc.km, ribside=\"bottom\", main=\"Income\")\nplot(p.km, pch = 20, col=rgb(1,1,1,0.6), add=TRUE)\n```\n\n::: {.cell-output-display}\n![](PPM_analysis_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n## Modeling point density as a function of two competing covariates: population density and income.\n\nWe will first develop two different models that we think might define the Walmart's point intensity. Recall that *intensity* is a property of the underlying \"process\" (one being defined by the distribution of population density and the other being defined by the distribution of income)--this differs from *density* which is associated with the observed pattern. These models are represented in our R script by a couple of \"raster\": a population raster and a distribution and income raster. These models will be  **alternate** models that we'll denote as `Mpop` and `Minc` in the script. The models' structure will follow the form of a logistics model, but note that the models can take on many different forms and different levels of complexity.\n\nWe'll also create the null model, `Mo`, which will assume a **spatially uniform** (homogeneous) covariate. In other words, `Mo` will define the model where we the intensity of the process is the same across the entire study extent.\n\n\n::: {.cell hash='PPM_analysis_cache/html/unnamed-chunk-5_8cdff594f0f397efcbedb3e2b0bc6c06'}\n\n```{.r .cell-code}\nMpop <- ppm(p.km ~ pop.km.log) # Population model\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Values of the covariate 'pop.km.log' were NA or undefined at 3.4% (17\nout of 504) of the quadrature points. Occurred while executing: ppm.ppp(Q =\np.km, trend = ~pop.km.log, data = NULL, interaction = NULL)\n```\n:::\n\n```{.r .cell-code}\nMinc <- ppm(p.km ~ inc.km)     # Income model\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Values of the covariate 'inc.km' were NA or undefined at 3.2% (16 out\nof 504) of the quadrature points. Occurred while executing: ppm.ppp(Q = p.km,\ntrend = ~inc.km, data = NULL, interaction = NULL)\n```\n:::\n\n```{.r .cell-code}\nMo   <- ppm(p.km ~ 1)          # Null model\n```\n:::\n\n\nLet's explore the model parameters. First, we'll look at `Mpop`.\n\n\n::: {.cell hash='PPM_analysis_cache/html/unnamed-chunk-6_881d0cc4adce05c3bc5b554be549722f'}\n\n```{.r .cell-code}\nMpop\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNonstationary Poisson process\n\nLog intensity:  ~pop.km.log\n\nFitted trend coefficients:\n(Intercept)  pop.km.log \n -10.111647    0.625803 \n\n              Estimate      S.E.     CI95.lo    CI95.hi Ztest       Zval\n(Intercept) -10.111647 0.7933272 -11.6665393 -8.5567540   *** -12.745872\npop.km.log    0.625803 0.1127980   0.4047229  0.8468831   ***   5.547996\nProblem:\n Values of the covariate 'pop.km.log' were NA or undefined at 3.4% (17 out of \n504) of the quadrature points\n```\n:::\n:::\n\n\nThe values of interest are the **intercept** (whose value is around `-10.1`) and the **coefficient** `pop.km.log` (whose value is around `0.63`). Using these values, we can construct the mathematical relationship (noting that we are using the logged population raster and not the original population raster values):\n\n\n$$\nWalmart\\ intensity(i)= e^{−10.1 + 0.63\\ log(population\\ density_i)}\n$$ The above equation can be interpreted as follows: if the population density is `0`, then the Walmart intensity is $e^{−10.1}$ which is very close to `0`. So for every unit increase of the *logged* population density (i.e. log of one person per square mile), there is a $e^{0.63}$ increase in Walmart intensity.\n\n\nLikewise, we can extract the parameters from the `Minc` model and construct its equation.\n\n\n::: {.cell hash='PPM_analysis_cache/html/unnamed-chunk-7_1441165cd2bee02f6ec5be684f29d1b9'}\n\n```{.r .cell-code}\nMinc\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNonstationary Poisson process\n\nLog intensity:  ~inc.km\n\nFitted trend coefficients:\n  (Intercept)        inc.km \n-5.576942e+00 -1.654792e-05 \n\n                 Estimate         S.E.       CI95.lo       CI95.hi Ztest\n(Intercept) -5.576942e+00 5.258426e-01 -6.607574e+00 -4.546309e+00   ***\ninc.km      -1.654792e-05 1.490546e-05 -4.576209e-05  1.266624e-05      \n                  Zval\n(Intercept) -10.605725\ninc.km       -1.110192\nProblem:\n Values of the covariate 'inc.km' were NA or undefined at 3.2% (16 out of 504) \nof the quadrature points\n```\n:::\n:::\n\n$$\nWalmart\\ intensity(i) = e^{−5.58\\ −1.66e^{−5}\\ Income(i)}\n$$ Note the negative (decreasing) relationship between income distribution and Walmart density.\n\n\nNext, we'll extract the null model results:\n\n\n::: {.cell hash='PPM_analysis_cache/html/unnamed-chunk-8_0480d7a4cb30ad819a1dbb1c710708a8'}\n\n```{.r .cell-code}\nMo\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStationary Poisson process\nIntensity: 0.002086305\n             Estimate      S.E.   CI95.lo   CI95.hi Ztest      Zval\nlog(lambda) -6.172361 0.1507557 -6.467836 -5.876885   *** -40.94281\n```\n:::\n:::\n\n\nThis gives us the following equation for the homogeneous process:\n\n\n$$\nWalmart\\ intensity(i) = e^{−6.17} = 0.00209\n$$\n\n\nwhich is nothing more than the number of stores per unit area (44 stores / 21,000km^2^ = 0.00209).\n\n## Plotting the competing models\n\n\n::: {.cell small.mar='true' hash='PPM_analysis_cache/html/unnamed-chunk-9_2de8243173c7351f14e585c45f0a2354'}\n\n```{.r .cell-code}\nOP <- par(mfrow = c(1,2), mar = c(4,4,2,1))  # This creates a two-pane plotting window\n\nplot(effectfun(Mpop, \"pop.km.log\", se.fit = TRUE), main = \"Population\",\n     ylab = \"Walmarts per km2\", xlab = \"Population density\", legend = FALSE)\n\nplot(effectfun(Minc, \"inc.km\", se.fit = TRUE), main = \"Income\",\n     ylab = \"Walmarts per km2\", xlab = \"Income\", legend = FALSE)\n\npar(OP) # This reverts our plot window back to a one-pane window\n```\n\n::: {.cell-output-display}\n![](PPM_analysis_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nNote the difference in relationships between the two models. In the first plot, we note an increasing relationship between Walmart intensity and population density; this is to be expected since you would not expect to see Walmart stores in underpopulated areas. In the second plot, we note an inverse relationship between Walmart intensity and income---i.e. as an area's income increases, the Walmart intensity decreases.\n\nThe grey envelopes encompass the 95% confidence interval; i.e. the true estimate (black line) can fall anywhere within this envelope. Note how the envelope broadens near the upper end of the population density values--this suggests wide uncertainty in the estimated model.\n\nTo assess how well the above models explain the relationship between covariate and Walmart intensity, we will turn to hypothesis testing.\n\n## Testing for covariate effect\n\nNow, let's compare the non-homogeneous covariates to the null model using a technique called the *likelihood ratio* test. Remember that the null model assumes that the intensity is homogeneous across the entire study area; what we want to know is *\"does the model with the covariate do a significantly better job in predicting Walmart densities than the null model?\"*\n\n\n::: {.cell hash='PPM_analysis_cache/html/unnamed-chunk-10_3b6a4f0beb17463d5342bad20a5671e4'}\n\n```{.r .cell-code}\nanova(Mo, Mpop, test = \"LRT\") # Compare null to population model\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Values of the covariate 'pop.km.log' were NA or undefined at 3.4% (17\nout of 504) of the quadrature points. Occurred while executing: ppm.ppp(Q =\np.km, trend = ~pop.km.log, data = NULL, interaction = NULL,\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Models were re-fitted after discarding quadrature points that were\nillegal under some of the models\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: ~1 \t Poisson\nModel 2: ~pop.km.log \t Poisson\n  Npar Df Deviance  Pr(>Chi)    \n1   18                          \n2   19  1   31.725 1.776e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell hash='PPM_analysis_cache/html/unnamed-chunk-11_98fb275b8617777fdc7295b34979ee5d'}\n\n```{.r .cell-code}\nanova(Mo, Minc, test = \"LRT\") # Compare null to income model\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Values of the covariate 'inc.km' were NA or undefined at 3.2% (16 out\nof 504) of the quadrature points. Occurred while executing: ppm.ppp(Q = p.km,\ntrend = ~inc.km, data = NULL, interaction = NULL,\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Models were re-fitted after discarding quadrature points that were\nillegal under some of the models\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: ~1 \t Poisson\nModel 2: ~inc.km \t Poisson\n  Npar Df Deviance Pr(>Chi)\n1   17                     \n2   18  1   1.3388   0.2473\n```\n:::\n:::\n\n\nWhat we are seeking is a small p-value (parameter `Pr(>Chi)` in the output). The smaller the value, the more confident we are in stating that the covariate does a better job in predicting Walmart intensity than the null model. For example, the p-value for the `Mpop` model (`Pr(>Chi) = 1.776e-08`) suggests that population density does a better job in predicting Walmart density than the null model `Mo`.\n\nThe p-value for `Minc`, on the other hand, is higher with a value of `Pr = 0.247` indicating that there is a 24.7% chance that we would be wrong in stating that income does a better job in predicting Walmart densities. To many, that probability is too high to reject the null.\n\nSo to summaries: of the two models we tested, it seems that population density does a better job at explaining the distribution of Walmarts (though it's not perfect) than the null model. Income distribution, on the other hand, does not improve on the null model.\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}